### ISSUE TITLE
[ctdb/ss] Test clustered mode in the default CI

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-operator#121]
Currently the tests for clustered SmbShares are not run in the CI. This is because the CI uses a single node k8s cluster with no ability to provision RWX PVCs.

At the bare minimum the test cluster *must* support Read-Write-Many. Ideally it would also support >=3 k8s nodes.

I don't know if the github CI is sufficient for this.

**Comment by phlogistonjohn** [comment]
We discussed this a bit in a call earlier today.
The current plan is to investigate the use of centos ci for this:
* get the needed integration set up
* create the ci jobs
* set up a three node cluster (probably use minikube)
* set up rook for rwx pvcs

After the above, the remaining work would be like what we currently have in the github actions with a few tweaks (probably).

The initial project setup work with be handled by @anoopcs9 with my help.

**Comment by anoopcs9** [comment]
Request for Samba project namespace: https://pagure.io/centos-infra/issue/537

**Comment by anoopcs9** [comment]
After fighting with various [issues](https://pagure.io/centos-infra/issues?status=Closed&search_pattern=cico&author=anoopcs&close_status=) we are now ready on our dedicated [**Samba Namespace**](https://jenkins-samba.apps.ocp.ci.centos.org/). Jobs and other scripts are currently residing under my GitHub username in [**samba-centosci**](https://github.com/anoopcs9/samba-centosci) repository. I have also setup a GitHub [workflows](https://github.com/anoopcs9/samba-centosci/tree/main/.github/workflows) to verify/update jobs as and when they are modified in the repository.

**Comment by anoopcs9** [comment]
We are progressing with a sample [job](https://jenkins-samba.apps.ocp.ci.centos.org/view/SINK/) on CentOS CI. Currently looking into a frequent `minikube` start [failure](https://github.com/kubernetes/minikube/issues/11459) on CentOS installed host.

**Comment by anoopcs9** [comment]
> Currently looking into a frequent `minikube` start [failure](https://github.com/kubernetes/minikube/issues/11459) on CentOS installed host.

This is now being fixed with https://github.com/kubernetes/minikube/pull/13482. Next step is to establish an internal CI registry for Samba project namespace to be used as local mirror.

**Comment by anoopcs9** [comment]
Updates:
* Internal CI registry up and running at _https://registry-samba.apps.ocp.ci.centos.org_
* Consumes new minikube release([v1.25.2](https://github.com/kubernetes/minikube/releases/tag/v1.25.2)) with required fixes
* Validation started for running clustered test cases. See planned [changes](https://github.com/anoopcs9/samba-operator/commits/add-centosci-scripts)

**Comment by anoopcs9** [comment]
CI [jobs](https://jenkins-samba.apps.ocp.ci.centos.org/view/SINK/) are setup to be run against each PR. Additionally they are triggered as nightly jobs.

**Comment by anoopcs9** [comment]
In the light of discussions around the need for running tests with 3 different Kubernetes versions, decision has been made to only run **_centos-ci/sink-clustered/mini-k8s-1.23_** against each PR to samba-operator repository. No change in nightly configured jobs.
