### ISSUE TITLE
YAML files "churn" when executing make commands

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-operator#140]
I think this is fallout from #131 

When I run commands such as `make manifests` many of the YAML files show as changed to git. However, I've not touched the sources. I think we should do one of the following:

* Configure our yaml generating tools to conform to the new styling
* Configure the make file to automatically format the output of `make manifests` and the like
* Change our formatting/linting rules to conform to the default output of the tools used for `make manifests` and the like.

**Comment by synarete** [comment]
Tools like `controller-gen` does not enforce strict output-yaml format (as required by `yamllint`). 
Option 2 (Configure the make file to automatically format the output of `make manifests`) is best IMHO.

**Comment by synarete** [comment]
Tools like `controller-gen` does not enforce strict output-yaml format (as required by `yamllint`). 
Option 2 (Configure the make file to automatically format the output of `make manifests`) is best IMHO.

**Comment by synarete** [comment]
https://github.com/samba-in-kubernetes/samba-operator/pull/143
