### ISSUE TITLE
 Document how to consume a share inside the k8s cluster

### ISSUE THREAD

**Issue by ibotty** [samba-in-kubernetes/samba-operator#174]
I used csi-driver-smb and a `pv`.  If that's the intended way, I can write some documentation.

In the future it would, of course, be great to allow consuming `smbshares` with pods in the same namespace without the administrator having to manually create a `pv`.

**Comment by phlogistonjohn** [comment]
Additional documentation would be very welcome! Thank you for the suggestion.

I agree that admins should not have to create the PVs manually. Longer term, for in-cluster provisioning, we hope to have the operator work with a CSI based provisioner for allocating shares and csi-driver-smb for mounting them. There's an experimental [samba-in-kubernetes/csi-provisioner-smb project](https://github.com/samba-in-kubernetes/csi-provisioner-smb)  that got started last year. We hope to revitalize that project soon as well as make it more efficient to dynamically create/delete shares in the operator (see #175)
