### ISSUE TITLE
Add centosci test target for kubernetes 1.24

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-operator#204]
No rush on this one, but we're testing our PRs on k8s 1.23 but 1.24 was released earlier this month. I think that we should target 1.24 (only) for a while and then consider widening the number of kube versions we test against later this year.  Feel free to discuss.

**Comment by anoopcs9** [comment]
This is something I accidentally got to try 2 weeks back with then latest minikube and it failed. I'll investigate more..

**Comment by anoopcs9** [comment]
```
May 28 06:27:49 minikube kubelet[4658]: Error: failed to parse kubelet flag: unknown flag: --cni-conf-dir
. . .
May 28 06:33:38 minikube kubelet[4652]: Error: failed to parse kubelet flag: unknown flag: --network-plugin
```
[Issue](https://github.com/kubernetes/minikube/issues/13945) reported is now closed but a release is yet to happen.

**Comment by phlogistonjohn** [comment]
Cool. Let's just keep an eye on minikube and try again once they release

**Comment by anoopcs9** [comment]
[samba_sink-mini-k8s-1.24-clustered](https://jenkins-samba.apps.ocp.ci.centos.org/job/samba_sink-mini-k8s-1.24-clustered/) is now created.
