### ISSUE TITLE
Test Stabilization: prevent tests from "stepping on" each other

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-operator#222]
Tests need to verify that they've cleaned the resources at teardown.
Tests should use unique names for resources. This will help avoid collisions, identify problems, and allow parallel runs in the future.

**Comment by anoopcs9** [comment]
> Tests need to verify that they've cleaned the resources at teardown.

This will most likely fix the following(very frequent) error on CentOS CI:
```
=== RUN   TestIntegration/createDelete/simple/TestCreateAndDelete
error: waiting for older pods to be cleaned: context deadline exceeded
    assertion_compare.go:313: 
        	Error Trace:	cleanup_test.go:157
        	Error:      	"3" is not greater than "3"
        	Test:       	TestIntegration/createDelete/simple/TestCreateAndDelete
        	Messages:   	[]
```
