### ISSUE TITLE
initializing posix permissions handler: OSError: [Errno 95] Operation not supported

### ISSUE THREAD

**Issue by Shadow2091** [samba-in-kubernetes/samba-operator#294]
Hello.
I am trying to create the first share. Installed controller v0.2 via make deploy. Pod <sharename> has been created but won't start.
### **Init container log:**
_2023-03-12 10:58:58,457: INFO: Ensuring share path: /mnt/3ec9e0ab-30e7-4eda-935c-f5aee9774188
2023-03-12 10:58:58,457: INFO: Updating permissions if needed: /mnt/3ec9e0ab-30e7-4eda-935c-f5aee9774188
2023-03-12 10:58:58,457: INFO: Using initializing posix permissions handler
Traceback (most recent call last):
  File "/usr/bin/samba-container", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/sambacc/commands/main.py", line 217, in main
    cfunc(CommandContext(cli))
  File "/usr/lib/python3.10/site-packages/sambacc/commands/initialize.py", line 91, in ensure_share_paths
    perms_handler(share.permissions_config(), path).update()
  File "/usr/lib/python3.10/site-packages/sambacc/permissions.py", line 143, in update
    if self.status_ok():
  File "/usr/lib/python3.10/site-packages/sambacc/permissions.py", line 136, in status_ok
    sval = self._get_status()
  File "/usr/lib/python3.10/site-packages/sambacc/permissions.py", line 152, in _get_status
    value = xattr.get(path, self._xattr, nofollow=True)
  File "/usr/lib/python3.10/site-packages/sambacc/_xattr.py", line 58, in get
    return xattr.get(item, name, **kwargs)
OSError: [Errno 95] Operation not supported_
### **SmbShare:**
_apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
spec:
  browseable: true
  readOnly: true
  storage:
    pvc:
      name: downloads-pvc_

### **PVC:**
_apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 999Gi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 999Gi
  volumeName: downloads
  storageClassName: static-nfs
  volumeMode: Filesystem_

**Comment by synarete** [comment]
@Shadow2091 What is the K8S cluster you are using? (minikube? openshift? other?)

**Comment by Shadow2091** [comment]
Vanilla K8S v1.25.4

**Comment by synarete** [comment]
@Shadow2091 Are you using nfs for your underlying pvc? If so, does your nfs export supports [File System Extended Attributes](https://datatracker.ietf.org/doc/rfc8276/) ?

**Comment by Shadow2091** [comment]
@synarete Yes, I am using NFS. PV connected with options
_ mountOptions:
    - hard
    - nfsvers=4.1_
The NFS source is Centos8Stream with options:
/storage/torrents/ k8s-worker01.home(rw,sync,no_subtree_check,no_root_squash)
And on K8S worker node:
_/var/lib/kubelet/pods/c5b44445-731b-4ac0-bdc8-a9b5cd360b58/volumes/kubernetes.io~nfs/downloads from nfs.home:/storage/torrents/downloads
 Flags: rw,relatime,vers=4.1,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.31,local_lock=none,addr=192.168.1.37_

**Comment by synarete** [comment]
@Shadow2091 Extended attributes over nfs (RFC 8276) is a relatively [new comer](https://lkml.iu.edu/hypermail/linux/kernel/2008.1/00599.html) to linux nfs server, and I suspect that it is not supported in your CentOS8 machine. Please make sure that is supported, both by the underlying file system and via nfs export. 

In order to validate extended-attributives support, try to do the following operations in both cases:

```shell

$ touch ./a
$ setfattr -n user.test -v 123456 ./a
$ getfattr -d ./a

```

**Comment by Shadow2091** [comment]
@synarete After switching PV to NFS 4.2 everything worked. Thanks for the help!

**Comment by phlogistonjohn** [comment]
I'm glad you were able to get this to work. I do want to note that there are general issues when re-exporting NFS over SMB. I highly recommend looking over the [Samba users's list](https://lists.samba.org/archive/samba/) and searching for NFS. There are other gotchas and performance issues that you might encounter. If these don't end up impacting you and everything works for your needs, great! I just want to make sure you are aware of the known issues.

**Comment by Shadow2091** [comment]
Thanks for the warnings. Yes, I understand the performance issues, but I use multiple VMs on my home server for personal use. In fact, all VMs are served by one AMD Epyc CPU and a pair of NVMe PM983. To compact resources, I decided to transfer some applications from VM to k8s, for which I needed your excellent application.
P.S. Is it possible to create a share with anonymous access?

**Comment by phlogistonjohn** [comment]
> Thanks for the warnings. Yes, I understand the performance issues, but I use multiple VMs on my home server for personal use. In fact, all VMs are served by one AMD Epyc CPU and a pair of NVMe PM983. To compact resources, I decided to transfer some applications from VM to k8s, for which I needed your excellent application.

OK, thank you!

> P.S. Is it possible to create a share with anonymous access?

Not today IIRC. Please feel free to create a new issue to request and track this feature
