### ISSUE TITLE
Document how to expose a share outside the k8s cluster

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-operator#91]
Support for additional configuration that will allow access to a share from outside the k8s cluster was added a few months back but not documented. In fact, all the basic docs are a bit out of date. These should be updated to reflect the current state of the operator.

**Comment by ibotty** [comment]
Isn't that done?  The documentation was clean enough to allow mounting from external.

**Comment by phlogistonjohn** [comment]
Yes, thank you for the reminder. Closing.
